"""add participation created_by

Revision ID: 623197337f74
Revises: 0f69948fc20b
Create Date: 2024-09-29 17:08:05.482257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623197337f74'
down_revision: Union[str, None] = '0f69948fc20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant") as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("participant_created_by_id_foreign_key",  'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant") as batch_op:
        batch_op.drop_constraint("participant_created_by_id_foreign_key", type_='foreignkey')
        batch_op.drop_column('created_by_id')
    # ### end Alembic commands ###
